Ntech.WebApp/Controllers/AssetsController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ntech.WebApp.Controllers
{
    public class AssetsController : Controller
    {
        public AssetsController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Ntech.WebApp/Controllers/DevicesController.cs
using Microsoft.AspNetCore.Mvc;

namespace Ntech.WebApp.Controllers
{
    public class DevicesController : Controller
    {
        public DevicesController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Ntech.WebApp/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace Ntech.WebApp.Controllers
{
    [Authorize(Roles = ApplicationConfig.SuperAdminRole)]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
    }
}

Ntech.WebApp/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Ntech.WebApp.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;

        public UsersController(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await _userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }
    }
}

Ntech.WebApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using Ntech.WebApp.Utility
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ntech Web App</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">

    @RenderSection("Styles", false)

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Ntech <sup>1.0</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            @if (SignInManager.IsSignedIn(User))
            {
                <!-- Nav Item - Dashboard -->
                <li class="nav-item active">
                    <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Heading -->
                <div class="sidebar-heading">Managements</div>

                <!-- Nav Item - Assets Collapse Menu -->
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapseAssets"
                        aria-expanded="true" aria-controls="collapseAssets">
                        <i class="fas fa-fw fa-cog"></i>
                        <span>Assets</span>
                    </a>
                    <div id="collapseAssets" class="collapse" aria-labelledby="headingAssets"
                        data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" asp-area="" asp-controller="Assets" asp-action="Index">Assets Information</a>
                        </div>
                    </div>
                    <div id="collapseAssets" class="collapse" aria-labelledby="headingAssets"
                     data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" asp-area="" asp-controller="Devices" asp-action="Index">Devices</a>
                        </div>
                    </div>
                    <div id="collapseAssets" class="collapse" aria-labelledby="headingAssets"
                     data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" asp-area="" asp-controller="Applications" asp-action="Index">Applications</a>
                        </div>
                    </div>
                </li>

                @if (User.IsInRole(ApplicationConfig.SuperAdminRole) || User.IsInRole(ApplicationConfig.AdminRole))
                {
                    <!-- Divider -->
                    <hr class="sidebar-divider">

                    <!-- Heading -->
                    <div class="sidebar-heading">Admin zone</div>

                    <li class="nav-item">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePermission"
                            aria-controls="collapsePermission">
                            <i class="fas fa-universal-access"></i>
                            <span>Permissions</span>
                        </a>
                        <div id="collapsePermission" class="collapse" aria-labelledby="headingTools"
                            data-parent="#accordionSidebar">
                            <div class="bg-white py-2 collapse-inner rounded">

                                <h6 class="collapse-header">Grant permission</h6>
                                <a class="collapse-item" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                <a class="collapse-item" asp-area="" asp-controller="Roles" asp-action="Index">Roles</a>

                            </div>
                        </div>
                    </li>
                }

                <!-- Nav Item - Admin -->
                <!--@if (User.IsInRole(ApplicationConfig.SuperAdminRole))
                {
                                                                    <li class="nav-item">
                                                                        <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">
                                                                            <i class="fas fa-fw fa-table"></i>
                                                                            <span>Create Admin User</span>
                                                                        </a>
                                                                    </li>
                }-->
            }
            else
            {
                <!-- Nav Item - Home -->
                <li class="nav-item active">
                    <a class="nav-link">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Home</span>
                    </a>
                </li>

                <!-- Nav Item - About -->
                <li class="nav-item active">
                    <a class="nav-link">
                        <i class="fa fa-address-book"></i>
                        <span>About us</span>
                    </a>
                </li>
            }

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <form class="form-inline">
                        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                            <i class="fa fa-bars"></i>
                        </button>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                @if (SignInManager.IsSignedIn(User))

                                {
                                    <span
                                        class="mr-2 d-none d-lg-inline text-gray-600 small">@UserManager.GetUserName(User)</span>
                                }

                                else

                                {
                                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">Anonymous User</span>
                                }
                                <img class="img-profile rounded-circle" src="~/img/undraw_profile.svg">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <partial name="_LoginPartial" />
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; NtechDevelopers 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>